---
roles:
  - src: https://github.com/rhythmictech/ansible-role-java.git
    scm: git
    version: v1.1.3
    name: java
  - src: https://github.com/rhythmictech/ansible-role-yumrepos.git
    scm: git
    version: 1.1.1
    name: yumrepos